version: '3.5'
services:
#Services
 lxde:
  build:
    context: build
    args:
     ENVPATH: lxde.env
  hostname: lxde
  environment:
   - DISPLAY=${DISPLAY}
  cap_add:
   - ALL
  volumes:
   - /tmp/.X11-unix:/tmp/.X11-unix
  #privileged: true
  #network_mode: host
